dataloader:
  train_dir: data/balanced
  test_dir: data/test
  data_type: fcg
  batch_size: 16
  pin_memory: false
  num_workers: 6

model:
  convolution_count: 0

trainer:
  max_epochs: 100
  gpus: null

hydra:
  run:
    dir: output/${dataloader.data_type}/${node_configuration.name}/conv_count=${model.convolution_count}
  sweep:
    dir: output/${dataloader.data_type}/${node_configuration.name}
    subdir: conv_count=${model.convolution_count}

defaults:
  - node_configuration: all