# @package _group_
name: wandb
args:
  project: malware_learning
  log_model: true
hparams:
  data_type: ${data.data_type}
  data_config: ${node_configuration.name}
  convolution_count: ${model.convolution_count}
