# @package _group_
name: wandb
args:
  project: LearningMalware
  name: ${prefix}-${dataloader.data_type}-${node_configuration.name}-conv_count=${model.convolution_count}
  log_model: true
  id: ${prefix}-${dataloader.data_type}-${node_configuration.name}-conv_count=${model.convolution_count}
